name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Running unit tests
        run: yarn test:unit

      - name: Running integration tests
        run: yarn test:integration
        env:
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}
