name: Test Docs Deployment

on:
  pull_request:
    branches: [main]
    paths: [docs/**]

jobs:
  test-deploy:
    name: Test Docs Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Test build
        working-directory: docs
        run: |
          yarn install --frozen-lockfile
          yarn build
