name: Update Wiki

on:
  push:
    paths:
      - '*/**'
    branches:
      - feat/wiki
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Clone Wiki Repo
        uses: actions/checkout@v2
        with:
          repository: 'Increment-Finance/increment-protocol.wiki'
          path: 'wiki'

      - uses: OrlovM/Wiki-Action@v1
        with:
          path: 'wiki'
          token: ${{ secrets.GITHUB_TOKEN }}
