name: Update Wiki

on:
  push:
    paths:
      - '*/**'
    branches:
      - feat/wiki
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: yarn

      - name: Init Yarn
        run: yarn install --frozen-lockfile

      - name: Sync Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: 'wiki'
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
