name: Update Wiki

on:
  push:
    paths:
      - 'contracts/**'
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: yarn

      - name: Init Yarn
        run: yarn install --frozen-lockfile

      - uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: 'wiki'
          AUTO_SIDEBAR: true
